# Generated by Django 4.2.2 on 2023-08-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_description_alter_products_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='worker_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='consuption',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
    ]
