# Generated by Django 4.2.2 on 2023-08-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_workers_worker_id_alter_products_consuption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='consuption',
        ),
        migrations.RemoveField(
            model_name='products',
            name='times',
        ),
    ]
