# Generated by Django 4.2.2 on 2023-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_products_consuption_remove_products_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='daily_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
