# Generated by Django 4.2.2 on 2023-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_daily_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='daily_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
