# Generated by Django 4.2.2 on 2023-08-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_active_alter_users_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(default=21623, max_length=5),
        ),
    ]
